spring.application.name=asz-inventory-api

app.frontend.origin=http://localhost:5173

app.members.csv-path=CSV/members.csv
app.drinks.csv-path=CSV/drinks.csv
app.bwbookings.csv-path=CSV/bwbookings.csv
app.bwdeposits.csv-path=CSV/bwdeposits.csv