spring.application.name=asz-inventory-api

app.frontend.origin=http://localhost:5173

app.members.csv-path=CSV/members.csv
app.drinks.csv-path=CSV/drinks.csv
app.bwbookings.csv-path=CSV/bwbookings.csv
app.deposits.csv-path=CSV/bwdeposits.csv
app.bwsnapshots.csv-path=CSV/bwsnapshots.csv
app.bwaccountbookings.csv-path=CSV/bwaccountbookings.csv
app.vendors.csv-path=CSV/vendors.csv
app.inventoryitems.csv-path=CSV/inventoryitems.csv